package org.dk.selenk.common.exception

enum class ErrorCodeDefinition {
    UNKNOWN_ERROR, NOT_SUPPORTED_ON_PLATFORM, TASK_NOT_SPECIFIED, INIT_DRIVER_ERROR, PLATFORM_NOT_SUPPORTED,
    AUTOMATION_TYPE_NO_SUPPORTED, APPIUM_URL_NOT_PROVIDED
}
